name: Go Generate

on:
  push:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "true"
          clean: true

      - name: Config Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main

      - name: Go generate
        run: |
          cd aiplan.go
          go generate ./...

      - name: Push to repo
        run: |
          git add .
          git commit -m "submodules update" || echo "No changes to commit"
          git push origin HEAD:main
